### ISSUE TITLE
Solvers behave differently from SciPy

### ISSUE THREAD

**Issue by yuan-yin** [juntang-zhuang/torch_ACA#2]
With the same method and the same options, some solvers in `torch_ACA` (including RK45 and Dopri5) give weird trajectories which are different from those simulated with SciPy. After correction of the code at https://github.com/juntang-zhuang/torch_ACA/blob/ae96d82d99226710bf5557c1af53dc19f41ffba5/torch_ACA/utils.py#L25
to
```
        hyperparams.update({'rtol': options['rtol']})
```
and disabling all PyTorch `state_dict` operations, the undesired behaviors can be observed via the following code: 
```
from torch_ACA.odesolver import odesolve
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt
import numpy as np
import torch
import scipy

np.random.seed(0)

alpha = 0.5
beta  = 0.5
delta = 0.5
gamma = 0.5

def lotka_volterra(t, x):
    if torch.is_tensor(x):
        d = torch.zeros_like(x)
    else:
        d = np.zeros(2)
    d[0] = alpha * x[0] - beta * x[0] * x[1]
    d[1] = delta * x[0] * x[1] - gamma * x[1] 
    return d

x0 = (np.random.random() + np.ones(2)).astype(np.float32)

t = np.linspace(0, 10., 1000)

x = solve_ivp(lotka_volterra, (0.0, 10.0), x0, method='RK45', t_eval=t, rtol=1e-3, atol=1e-6).y

plt.plot(x[0], x[1])

x0 = torch.from_numpy(x0)

options = {}
options.update({'method': 'RK45'})
options.update({'t0': 0.0})
options.update({'t1': 10.0})
options.update({'rtol': 1e-3})
options.update({'atol': 1e-6})
options.update({'t_eval':t.tolist()})

x = odesolve(lotka_volterra, x0, options)

plt.plot(x[:, 0], x[:, 1])
plt.show()
```
giving:
![demo](https://user-images.githubusercontent.com/11399307/93687473-9fcd8d00-fabe-11ea-9456-fe7f2d3a1843.png)

The solver works fine with your original code (commit https://github.com/juntang-zhuang/torch_ACA/commit/f214eda06f467f8826981bbb821199f6052b14e1) since `rtol` and `atol` are accidentally set to the same value of `1e-6`. Maybe there are some problems in the function adjusting the step size? (Probably in the functions involving `rtol`, but I did not find out the bug...)

Thank you for your attention in advance.

**Comment by juntang-zhuang** [comment]
Thanks a lot for pointing this out, this is an important bug.
I found the error to be  https://github.com/juntang-zhuang/torch_ACA/blob/ae96d82d99226710bf5557c1af53dc19f41ffba5/torch_ACA/odesolver/adaptive_grid_solver.py/#L523
it should NOT multiply time step, because the variables (or k ) is already scaled by time step as in https://github.com/juntang-zhuang/torch_ACA/blob/ae96d82d99226710bf5557c1af53dc19f41ffba5/torch_ACA/odesolver/adaptive_grid_solver.py/#L601
I fixed these errors in a new branch "dense_state2".
Here is the result of your example above, I added the test code https://github.com/juntang-zhuang/torch_ACA/blob/dense_state2/test_lotka.py.

![Figure_1](https://user-images.githubusercontent.com/44451229/93822327-0f15bf00-fc2e-11ea-811a-378c873616fc.png)

**Comment by yuan-yin** [comment]
Thanks a lot for your efforts!
